"""Step 4: Generate Prolog facts from JSON and run compliance checks."""
import json
import subprocess
from pathlib import Path


def run_prolog(facts_json_path: Path, case_id: str, vault_dir: Path,
               prolog_dir: Path) -> Path:
    """Generate Prolog facts, run Section 30 + 29A checks.

    Returns path to results JSON file.
    """
    with open(facts_json_path, 'r') as f:
        data = json.load(f)

    s30 = data['section30_facts']
    s29 = data['section29A_facts']
    fin = data['financial_data']
    notes = data.get('compliance_notes', [])

    plan_id = s30['plan_id']

    # Generate Prolog facts
    facts_pl = _generate_prolog_facts(plan_id, s30, s29, fin, notes)
    facts_pl_path = prolog_dir / f"{case_id}_facts.pl"
    with open(facts_pl_path, 'w') as f:
        f.write(facts_pl)
    print(f"  Prolog facts → {facts_pl_path.name}")

    # Run Section 30 compliance
    result_s30 = subprocess.run(
        ['swipl', '-s', str(prolog_dir / 'section30_compliance.pl'),
         '-s', str(facts_pl_path), '-g', f'check_compliance({plan_id})'],
        capture_output=True, text=True
    )

    s30_output = result_s30.stdout
    if result_s30.stderr:
        for line in result_s30.stderr.split('\n'):
            if 'ERROR' in line:
                s30_output += f"\nERROR: {line}"

    # Run conditional compliance (3-state model)
    result_cond = subprocess.run(
        ['swipl', '-s', str(prolog_dir / 'section30_compliance.pl'),
         '-s', str(prolog_dir / 'conditional_compliance.pl'),
         '-s', str(facts_pl_path), '-g', f'check_conditional_compliance({plan_id})'],
        capture_output=True, text=True
    )
    cond_output = result_cond.stdout
    if result_cond.stderr:
        for line in result_cond.stderr.split('\n'):
            if 'ERROR' in line:
                cond_output += f"\nERROR: {line}"

    # Run Section 29A eligibility for first RA
    ra_names = [ra['name'].lower().replace(' ', '_').replace('.', '').replace(',', '')
                for ra in s29.get('resolution_applicants', [])]
    if ra_names:
        ra_atom = ra_names[0]
        s29_goal = f"ignore((is_eligible_29A({ra_atom}) -> writeln('ELIGIBLE') ; writeln('NOT ELIGIBLE'))), halt."
    else:
        s29_goal = "writeln('NO RA FOUND'), halt."
        ra_atom = "unknown"

    result_s29 = subprocess.run(
        ['swipl', '-s', str(prolog_dir / 'section29A_eligibility.pl'),
         '-s', str(facts_pl_path), '-g', s29_goal],
        capture_output=True, text=True
    )
    s29_output = result_s29.stdout

    # Run Regulation 38 detailed check
    result_reg38 = subprocess.run(
        ['swipl', '-s', str(prolog_dir / 'reg38_details.pl'),
         '-s', str(facts_pl_path), '-g', f'check_reg38({plan_id})'],
        capture_output=True, text=True
    )
    reg38_output = result_reg38.stdout
    if result_reg38.stderr:
        for line in result_reg38.stderr.split('\n'):
            if 'ERROR' in line:
                reg38_output += f"\nERROR: {line}"

    # Run Section 29A(j) connected person analysis
    if ra_names:
        s29j_goal = f"check_connected_persons({ra_atom}), halt."
    else:
        s29j_goal = "writeln('NO RA FOUND'), halt."

    result_s29j = subprocess.run(
        ['swipl', '-s', str(prolog_dir / 'section29A_eligibility.pl'),
         '-s', str(prolog_dir / 'section29A_connected.pl'),
         '-s', str(facts_pl_path), '-g', s29j_goal],
        capture_output=True, text=True
    )
    s29j_output = result_s29j.stdout

    # Run Financial & Timeline validator
    result_fin = subprocess.run(
        ['swipl', '-s', str(prolog_dir / 'financial_validator.pl'),
         '-s', str(facts_pl_path), '-g', f'check_financial({plan_id})'],
        capture_output=True, text=True
    )
    fin_output = result_fin.stdout
    if result_fin.stderr:
        for line in result_fin.stderr.split('\n'):
            if 'ERROR' in line:
                fin_output += f"\nERROR: {line}"

    # Save results
    results = {
        "section30_output": s30_output,
        "section29A_output": s29_output,
        "reg38_output": reg38_output,
        "section29A_connected_output": s29j_output,
        "conditional_compliance_output": cond_output,
        "financial_output": fin_output,
        "plan_id": plan_id,
        "ra_atom": ra_atom,
    }
    results_path = vault_dir / f"{case_id}_results.json"
    with open(results_path, 'w') as f:
        json.dump(results, f, indent=4)

    print(f"  Compliance results → {results_path.name}")
    return results_path


def _generate_prolog_facts(plan_id: str, s30: dict, s29: dict, fin: dict, notes: list) -> str:
    """Generate Prolog fact predicates from structured JSON."""
    def pval(val):
        if isinstance(val, str):
            return val
        return val

    lines = []
    lines.append(f"% --- Auto-generated facts for {plan_id} ---")
    lines.append(f"% Generated by LexAI-Precision pipeline")
    lines.append("")

    # Discontiguous declarations
    for pred in ['undischarged_insolvent', 'wilful_defaulter', 'npa_status',
                 'convicted_offence', 'disqualified_director', 'prohibited_by_sebi',
                 'involved_in_fraudulent_transactions', 'guarantee_invoked', 'guarantee_unpaid']:
        lines.append(f":- discontiguous {pred}/2.")
    lines.append(":- discontiguous guarantee_executed/3.")
    lines.append("")

    # Section 30 facts
    lines.append("% ===== SECTION 30(2) & REGULATION 38 =====")
    lines.append("")
    lines.append(f"plan_detail({plan_id}, cirp_cost_payment, {pval(s30['cirp_cost_payment'])}).")
    lines.append(f"plan_detail({plan_id}, oc_payment, {int(s30['oc_payment'] * 10000000)}).")
    lines.append(f"plan_detail({plan_id}, liquidation_value_oc, {int(s30['liquidation_value_oc'] * 10000000)}).")
    lines.append(f"plan_detail({plan_id}, waterfall_value_oc, {int(s30['waterfall_value_oc'] * 10000000)}).")
    lines.append(f"plan_detail({plan_id}, dissenting_fc_payment, {pval(s30['dissenting_fc_payment'])}).")
    lines.append(f"plan_detail({plan_id}, management_post_approval, {pval(s30['management_post_approval'])}).")
    lines.append(f"plan_detail({plan_id}, supervision_mechanism, {pval(s30['supervision_mechanism'])}).")
    lines.append(f"plan_detail({plan_id}, contravenes_any_law, {pval(s30['contravenes_any_law'])}).")
    lines.append(f"plan_detail({plan_id}, affidavit_29A_submitted, {pval(s30['affidavit_29A_submitted'])}).")
    lines.append(f"plan_detail({plan_id}, stakeholder_interest_statement, {pval(s30.get('stakeholder_interest_statement', 'not_mentioned'))}).")
    lines.append(f"plan_detail({plan_id}, implementation_timeline, {s30.get('implementation_timeline_months', 'null')}).")
    lines.append(f"plan_detail({plan_id}, earnest_money_submitted, {pval(s30.get('earnest_money_submitted', 'not_mentioned'))}).")
    lines.append(f"plan_detail({plan_id}, conditions_precedent_listed, {pval(s30.get('conditions_precedent_listed', 'not_mentioned'))}).")
    lines.append("")

    # Section 29A facts
    lines.append("% ===== SECTION 29A ELIGIBILITY =====")
    for ra in s29.get('resolution_applicants', []):
        name = ra['name'].lower().replace(' ', '_').replace('.', '').replace(',', '')
        lines.append(f"% Resolution Applicant: {ra['name']}")
        lines.append(f"undischarged_insolvent({name}, {ra['undischarged_insolvent']}).")
        lines.append(f"wilful_defaulter({name}, {ra['wilful_defaulter']}).")
        lines.append(f"npa_status({name}, {ra['npa_status']}).")
        lines.append(f"convicted_offence({name}, {ra['convicted_offence']}).")
        lines.append(f"disqualified_director({name}, {ra['disqualified_director']}).")
        lines.append(f"prohibited_by_sebi({name}, {ra['prohibited_by_sebi']}).")
        lines.append(f"involved_in_fraudulent_transactions({name}, {ra['involved_in_fraudulent_transactions']}).")
        lines.append(f"guarantee_executed({name}, corporate_debtor, {ra['guarantee_executed_for_cd']}).")
        lines.append(f"guarantee_invoked({name}, {ra['guarantee_invoked']}).")
        lines.append(f"guarantee_unpaid({name}, {ra['guarantee_unpaid']}).")
        lines.append("")

    # Connected persons
    for cp in s29.get('connected_persons', []):
        ra_name = cp['connected_to'].lower().replace(' ', '_').replace('.', '').replace(',', '')
        cp_name = cp['name'].lower().replace(' ', '_').replace('.', '').replace(',', '')
        lines.append(f"connected_person({ra_name}, {cp_name}).")
        lines.append(f"undischarged_insolvent({cp_name}, {cp['undischarged_insolvent']}).")
        lines.append(f"wilful_defaulter({cp_name}, {cp['wilful_defaulter']}).")
        lines.append(f"npa_status({cp_name}, {cp['npa_status']}).")
        lines.append(f"convicted_offence({cp_name}, {cp['convicted_offence']}).")
        lines.append(f"disqualified_director({cp_name}, {cp['disqualified_director']}).")
        lines.append(f"prohibited_by_sebi({cp_name}, {cp['prohibited_by_sebi']}).")
        lines.append(f"involved_in_fraudulent_transactions({cp_name}, {cp['involved_in_fraudulent_transactions']}).")
        lines.append("")

    # Financial data
    lines.append("% ===== FINANCIAL DATA =====")
    lines.append(f"plan_detail({plan_id}, total_claims_cr, {fin.get('total_claims_admitted_cr', 0)}).")
    lines.append(f"plan_detail({plan_id}, home_buyer_claims_cr, {fin.get('home_buyer_claims_cr', 0)}).")
    lines.append(f"plan_detail({plan_id}, fc_claims_cr, {fin.get('financial_creditor_claims_cr', 0)}).")
    lines.append(f"plan_detail({plan_id}, oc_claims_cr, {fin.get('operational_creditor_claims_cr', 0)}).")
    lines.append(f"plan_detail({plan_id}, cirp_cost_cr, {fin.get('cirp_cost_cr', 0)}).")
    lines.append(f"plan_detail({plan_id}, project_completion_cost_cr, {fin.get('project_completion_cost_cr', 0)}).")
    lines.append(f"plan_detail({plan_id}, earnest_money_cr, {fin.get('earnest_money_cr', 0)}).")
    lines.append(f"plan_detail({plan_id}, dtcp_dues_principal_cr, {fin.get('dtcp_dues_principal_cr', 0)}).")
    lines.append(f"plan_detail({plan_id}, payment_to_other_fcs_pct, {fin.get('payment_to_other_fcs_percentage', 0)}).")
    lines.append("")

    # Compliance notes
    lines.append("% ===== COMPLIANCE NOTES =====")
    for i, note in enumerate(notes, 1):
        lines.append(f"% Note {i}: {note}")

    return '\n'.join(lines)